import type { Product } from "@/components/ProductCard";

export const marketplaceProducts: Product[] = [
  {
    id: "m1",
    name: "JIMIN 'FACE' Photocard Set",
    group: "BTS",
    category: "Photocards",
    price: 24.99,
    estimatedValue: 28.0,
    image: "https://images.unsplash.com/photo-1614680376593-902f74cf0d41?w=400&h=400&fit=crop",
    seller: "kpoptrader99",
    condition: "Mint",
    rarityRating: "Rare",
  },
  {
    id: "m2",
    name: "NewJeans 1st EP 'New Jeans'",
    group: "NewJeans",
    category: "Albums",
    price: 32.0,
    estimatedValue: 30.0,
    image: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400&h=400&fit=crop",
    seller: "bunnystan",
    condition: "Like New",
    rarityRating: "Common",
  },
  {
    id: "m3",
    name: "BLACKPINK Official Lightstick Ver.2",
    group: "BLACKPINK",
    category: "Lightsticks",
    price: 55.0,
    estimatedValue: 52.0,
    image: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=400&h=400&fit=crop",
    seller: "blinkshop",
    condition: "New",
    rarityRating: "Uncommon",
  },
  {
    id: "m4",
    name: "Stray Kids SKZOO Plush - Leebit",
    group: "Stray Kids",
    category: "Plushies",
    price: 38.0,
    estimatedValue: 45.0,
    image: "https://images.unsplash.com/photo-1559715541-5daf8a0296d0?w=400&h=400&fit=crop",
    seller: "stayfan",
    condition: "New w/ Tags",
    rarityRating: "Very Rare",
  },
  {
    id: "m5",
    name: "IVE 'I'VE MINE' Poster Set",
    group: "IVE",
    category: "Posters",
    price: 15.0,
    estimatedValue: 14.0,
    image: "https://images.unsplash.com/photo-1598387993441-a364f854c3e1?w=400&h=400&fit=crop",
    seller: "divecollect",
    condition: "Mint",
    rarityRating: "Common",
  },
  {
    id: "m6",
    name: "LE SSERAFIM Mini Figure - Kazuha",
    group: "LE SSERAFIM",
    category: "Figurines",
    price: 42.0,
    estimatedValue: 35.0,
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=400&h=400&fit=crop",
    seller: "fearnot_merch",
    condition: "New",
    rarityRating: "Rare",
  },
  {
    id: "m7",
    name: "TWICE 'Ready To Be' Album",
    group: "TWICE",
    category: "Albums",
    price: 22.0,
    estimatedValue: 25.0,
    image: "https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=400&h=400&fit=crop",
    seller: "onceshop",
    condition: "Sealed",
    rarityRating: "Common",
  },
  {
    id: "m8",
    name: "aespa Official Lightstick",
    group: "aespa",
    category: "Lightsticks",
    price: 60.0,
    estimatedValue: 58.0,
    image: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=400&h=400&fit=crop",
    seller: "myscollector",
    condition: "New",
    rarityRating: "Uncommon",
  },
  {
    id: "m9",
    name: "BTS V 'Layover' Photocard",
    group: "BTS",
    category: "Photocards",
    price: 18.0,
    estimatedValue: 22.0,
    image: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400&h=400&fit=crop",
    seller: "taetaefan",
    condition: "Mint",
    rarityRating: "Ultra Rare",
  },
  {
    id: "m10",
    name: "SEVENTEEN 'FML' Album Deluxe",
    group: "SEVENTEEN",
    category: "Albums",
    price: 45.0,
    estimatedValue: 40.0,
    image: "https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=400&h=400&fit=crop",
    seller: "caratshop",
    condition: "Sealed",
    rarityRating: "Uncommon",
  },
  {
    id: "m11",
    name: "ENHYPEN Official Lightstick",
    group: "ENHYPEN",
    category: "Lightsticks",
    price: 50.0,
    estimatedValue: 48.0,
    image: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=400&h=400&fit=crop",
    seller: "engene_store",
    condition: "New",
    rarityRating: "Common",
  },
  {
    id: "m12",
    name: "ATEEZ Treasure EP Poster",
    group: "ATEEZ",
    category: "Posters",
    price: 12.0,
    estimatedValue: 15.0,
    image: "https://images.unsplash.com/photo-1598387993441-a364f854c3e1?w=400&h=400&fit=crop",
    seller: "atiny_merch",
    condition: "Good",
    rarityRating: "Legendary",
  },
];
